### PR TITLE
Update decentral heat-pump costs

### PR DESCRIPTION
**Pull request by yerbol-akhmetov**
Good day. I propose here to update the costs of the decentral heat pumps. The modifications are motivated by `pypsa/pypsa-ariadne`.

### CODE REVIEW

**Review by martacki — APPROVED** [review]
LGTM! Ready for merge?

**Comment by yerbol-akhmetov** [comment]
> LGTM! Ready for merge?

Still testing. Somehow capital cost for heat pumps reduced. Checking why.

**Comment by yerbol-akhmetov** [comment]
@martacki, now I think it can be merged. I have changed to 1H and removed `weighting_by_building_types`.

**Review by martacki — APPROVED** [review]
Thanks, looks good! You also checked that the `residential_heat_restriction_value` are consistent, as well as `reduce_space_heat_exogenously = false` everywhere, according to your comment on discord. So merging

**Pull request merged**
